
ray_max_docs_limit: null
base_dir: /mnt/gcs_bucket/ray_clustering_output
num_blocks: 1000
base_stage:
  max_docs: 5000
  tfidf: 
      train:
        n_components: 128
        random_seed: 42
        batch_size: 1024
        num_cpus: 210

      inference:
        num_cpus: 5
        batch_size: 1024
        concurrency: 200
  kmeans:
      train:
        batch_size: 2048
        iter_limit: 5

      inference:
        batch_size: 8192
        num_cpus: 20
        concurrency: 10

stages_list:
  - name: stage1
    pretty_name: "Stage 1"
    cluster_col_name: cluster_A
    kmeans:
      n_clusters: 10
  - name: stage2
    pretty_name: "Stage 2"
    cluster_col_name: cluster_B
    kmeans:
      n_clusters: 10