
ray_max_docs_limit: null
base_dir: /mnt/gcs_bucket/ray_clustering_output
num_blocks: 1000
base_stage:
  max_docs: 50000
  tfidf: 
      train:
        n_components: 128
        random_seed: 42
        batch_size: 1024
      inference:
        cpus: 5
        batch_size: 1024
        concurrency: 100
  kmeans:
      train:
        batch_size: 1024
        iter_limit: 20

      inference:
        batch_size: 8192
        num_cpus: 20
        concurrency: 10

stages_list:
  - name: stage1
    cluster_col_name: cluster_A
    kmeans:
      n_clusters: 10
  # - name: stage2
  #   kmeans:
  #     n_clusters: 10